OUTPUT_DIR: ./output/waymo
OBJECT_LIST_PATH: ./data/waymo/splits/bench_list.json
CKPT_PATH: ./ckpts/waymo/latest.pth
EXP:
  MEAN_CODE_PATH: ./ckpts/waymo/mean.npz
LOSS:
  CD_WEIGHT: 0.1
  CD_SMOOTH_L1_LOSS_BETA: 0.05
  SHAPE_LOSS_TYPE: smooth_l1
  USE_MC: True
CD_LOSS:
  USE_PREV_PC: true
  USE_INIT_PC: true
  USE_AGG_PC: true
  PREV_PC_DIR: double
  INIT_PC_DIR: double
  AGG_PC_DIR: y-x
  MERGE_INIT_TO_PREV: false
  MERGE_AGG_TO_PREV: false
SEARCH_CODE:
  FINETUNE_FIRST_FRAME: true
  IF_FINETUNE: true
  PREV_REG_WEIGHT: 0
  INIT_REG_WEIGHT: 20
  ZERO_REG_WEIGHT: 10
  ITER_NUM: 20
  POLICY: agg